// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxB4PiYblKeBBZzgHtsZ1b7fMTLMi_7YY',
    appId: '1:559550843585:web:70e911b9a008a8a4a72240',
    messagingSenderId: '559550843585',
    projectId: 't-a-m-ua-v2',
    authDomain: 't-a-m-ua-v2.firebaseapp.com',
    databaseURL: 'https://t-a-m-ua-v2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 't-a-m-ua-v2.appspot.com',
    measurementId: 'G-Y6QQ6TNQJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaWEwBrHs4QyRNGYTBikJoz7Ld-o1Pw60',
    appId: '1:559550843585:android:1e7b0591b8eacf4aa72240',
    messagingSenderId: '559550843585',
    projectId: 't-a-m-ua-v2',
    databaseURL: 'https://t-a-m-ua-v2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 't-a-m-ua-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6qb5QCMNjH-SNnypklBI-hMUXBwmYDPQ',
    appId: '1:559550843585:ios:b9f89b1b520f9feea72240',
    messagingSenderId: '559550843585',
    projectId: 't-a-m-ua-v2',
    databaseURL: 'https://t-a-m-ua-v2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 't-a-m-ua-v2.appspot.com',
    iosClientId: '559550843585-dqpmkp22dmlsp4412mm52qkjk6i5gbmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tamAppV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6qb5QCMNjH-SNnypklBI-hMUXBwmYDPQ',
    appId: '1:559550843585:ios:b9f89b1b520f9feea72240',
    messagingSenderId: '559550843585',
    projectId: 't-a-m-ua-v2',
    databaseURL: 'https://t-a-m-ua-v2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 't-a-m-ua-v2.appspot.com',
    iosClientId: '559550843585-dqpmkp22dmlsp4412mm52qkjk6i5gbmc.apps.googleusercontent.com',
    iosBundleId: 'com.example.tamAppV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxB4PiYblKeBBZzgHtsZ1b7fMTLMi_7YY',
    appId: '1:559550843585:web:eefc2167b267674aa72240',
    messagingSenderId: '559550843585',
    projectId: 't-a-m-ua-v2',
    authDomain: 't-a-m-ua-v2.firebaseapp.com',
    databaseURL: 'https://t-a-m-ua-v2-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 't-a-m-ua-v2.appspot.com',
    measurementId: 'G-TL3RBQ5GP0',
  );

}